### ISSUE TITLE
Maven repoisitory not works

### ISSUE THREAD

**Issue by glebreutov** [serkan-ozal/mysafe#1]
https://github.com/serkan-ozal/maven-repository/raw/master/  returns 404

**Comment by serkan-ozal** [comment]
Hi @glebreutov 
https://github.com/serkan-ozal/maven-repository/tree/master/ should be OK.
Could you please verify?

**Comment by glebreutov** [comment]
Thanks for quick answer. 

"https://github.com/serkan-ozal/maven-repository/tree/master/ " shows valid GitHub page, but maven doesn't recognize it as repository.

**Comment by serkan-ozal** [comment]
Hi @glebreutov 
Yes https://github.com/serkan-ozal/maven-repository/raw/master/  cannot be accessed directly from URL but adding it to repositories in the pom.xml should work.

Can you try by adding this configuration:

``` xml
<repositories>
    ...
    <repository>
        <id>serkanozal-maven-repository</id>
        <url>https://github.com/serkan-ozal/maven-repository/raw/master/</url>
    </repository>
    ...
</repositories>
```
